### ISSUE TITLE
Webserver Errors in logs [all versions]

### ISSUE THREAD

**Issue by Miamlya** [JonasunderscoreJones/McWebserver#6]
Fabric 1.20.1
Server doesn't shut down. It just froze. Here is error:
```
[07:17:12] [McWebserver-main/ERROR]: Uncaught exception in thread "McWebserver-main"
java.lang.NoClassDefFoundError: com/roxstudio/utils/CUrl
        at me.jonasjones.mcwebserver.web.ServerHandler.lambda$start$0(ServerHandler.java:31) ~[mcwebserver-fabric-quilt-0.3.2.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.roxstudio.utils.CUrl
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 2 more
[07:17:40] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.2.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:17:40] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.2.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by JonasunderscoreJones** [comment]
Thank You for bringing this to my attention. fixing it asap!

**Comment by JonasunderscoreJones** [comment]
I pushed a fix ([3fd5ae2](https://github.com/J-onasJones/McWebserver/commit/3fd5ae28aa40432ee0e9c452fb97bd8cadae4c94)) and published it under version `0.3.3` to modrinth and curseforge as usual.

**Comment by Miamlya** [comment]
Thank you. There are still some errors in the console:

```
[06:27:56] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T06:27:56.101435107Z)
[06:56:36] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T06:56:36.310339256Z)
[06:56:36] [McWebserver-worker/INFO]: File index.html of type text/html returned
[06:56:36] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T06:56:36.311995779Z)
[06:56:36] [McWebserver-worker/INFO]: Connection closed.
[06:56:36] [McWebserver-worker/INFO]: File joker.webp of type application/octet-stream returned
[06:56:36] [McWebserver-worker/INFO]: Connection closed.
[06:56:37] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T06:56:37.487098631Z)
[06:56:37] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T06:56:37.490072278Z)
[06:56:37] [McWebserver-worker/ERROR]: File favicon.png not found
[06:56:37] [McWebserver-worker/INFO]: Connection closed.
[06:56:44] [McWebserver-worker/INFO]: Connection closed.
[06:56:44] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:03:35] [Netty Epoll Server IO #0/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null
[07:11:43] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T07:11:43.504784113Z)
[07:11:43] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T07:11:43.505299640Z)
[07:11:50] [McWebserver-worker/INFO]: Connection closed.
[07:11:50] [McWebserver-worker/INFO]: Connection closed.
[07:11:50] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:11:50] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:12:05] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T07:12:05.377253136Z)
[07:12:05] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T07:12:05.381719814Z)
[07:12:10] [McWebserver-worker/INFO]: Connection closed.
[07:12:10] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:12:10] [McWebserver-worker/INFO]: Connection closed.
[07:12:10] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:12:39] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T07:12:39.408361597Z)
[07:12:39] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T07:12:39.408764085Z)
[07:13:05] [McWebserver-worker/INFO]: Connection closed.
[07:13:05] [McWebserver-worker/INFO]: Connection closed.
[07:13:05] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:13:05] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:15:44] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T07:15:44.950904352Z)
[07:15:44] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T07:15:44.952720628Z)
[07:15:50] [McWebserver-worker/INFO]: Connection closed.
[07:15:50] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:15:50] [McWebserver-worker/INFO]: Connection closed.
[07:15:50] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[08:17:17] [Netty Epoll Server IO #0/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null
```

**Comment by Miamlya** [comment]
Makes console a bit messy :D

**Comment by JonasunderscoreJones** [comment]
that is ominous. I have never seen this happen. could you describe how this happens? I can see that you are requesting a `joker.webp` and then in the next request, the error appears

**Comment by Miamlya** [comment]
It happens just randomly, maybe some users try to access some files that doesn't exist.
```
[20:48:59] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T20:48:59.490229631Z)
[20:48:59] [McWebserver-worker/ERROR]: Error with file not found exception : /home/container/webserver/404.html
[20:48:59] [McWebserver-worker/INFO]: Connection closed.
[20:49:00] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T20:49:00.628260218Z)
[20:49:00] [McWebserver-worker/ERROR]: Error with file not found exception : /home/container/webserver/404.html
[20:49:00] [McWebserver-worker/INFO]: Connection closed.
[20:49:00] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T20:49:00.634086384Z)
[20:49:10] [McWebserver-worker/ERROR]: Error with file not found exception : /home/container/webserver/404.html
[20:49:10] [McWebserver-worker/INFO]: Connection closed.
[20:49:10] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T20:49:10.624301771Z)
[20:49:10] [McWebserver-worker/ERROR]: Error with file not found exception : /home/container/webserver/404.html
[20:49:10] [McWebserver-worker/INFO]: Connection closed.
[20:49:14] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T20:49:14.080422898Z)
[20:49:14] [McWebserver-webserver/INFO]: Connection opened. (2024-01-10T20:49:14.081560628Z)
[20:49:18] [McWebserver-worker/ERROR]: Server error : java.net.SocketException: Broken pipe
[20:49:18] [McWebserver-worker/INFO]: Connection closed.
[20:50:41] [McWebserver-worker/INFO]: Connection closed.
[20:50:41] [McWebserver-worker/ERROR]: Uncaught exception in thread "McWebserver-worker"
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.util.StringTokenizer.<init>(StringTokenizer.java:197) ~[?:?]
        at java.util.StringTokenizer.<init>(StringTokenizer.java:234) ~[?:?]
        at me.jonasjones.mcwebserver.web.HttpServer.run(HttpServer.java:113) ~[mcwebserver-fabric-quilt-0.3.3.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[21:00:24] [Netty Epoll Server IO #3/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null

```

Maybe add if statement , or exception for null cases so it just doesn't spam in the console.

**Comment by JonasunderscoreJones** [comment]
the error about the 404 page is something I need to fix indeed, but it's not the NullPointerException. if a resource doesn't exist, it returns 404 automatically. though the system isn't totally thought out since if the 404 page doesn't exist it spams the console with the error that that file isn't present. If you would like to remove these kinds of logs all together, there is an option `logger.verbose` in the config file of the mod that allows you to toggle all the webserver logs.

I will investigate the error when I have the time :)

**Comment by JonasunderscoreJones** [comment]
I added a simple if statement like you said. I wasn't even aware that this edgecase could happen. If I have identified the problem correctly, it should work (commit: 0f26e4a in branch: errorlogfix).

here is a build for you to try: http://cdn.jonasjones.dev/misc/mcwebserver-fabric-quilt-0.3.3-hotfixmaybe.jar

**Comment by Miamlya** [comment]
Yup, it's fixed now
